version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: designerbot_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: designerbot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3Bgn1JJu
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: